### ISSUE TITLE
80页“寻找事件接受者”部分描述不准确

### ISSUE THREAD

**Issue by zfq** [AloneMonkey/iOSREBook-issues#20]
* 印次: 第1次印刷
* 位置: 80页'“寻找事件接受者中”的“寻找最合适的视图的过程如图4-12所示”那一部分'
* 问题: 步骤应该是先调用hitTest:withEvent:方法，在hitTest:withEvent:方法中才会调用pointInSide:withEvent方法
* 修改: 建议将第一步的内容修改成如下内容，第二步内容不变。
(1) 调用当前视图的hitTest:withEvent方法，此hitTest:withEvent方法内部会调用pointInSide:withEvent方法来判断触摸点是否在当前视图内。

**Comment by AloneMonkey** [comment]
恩，根据图来是先调用`hitTest:withEvent:`内部调用`pointInSide:withEvent`，这里省去了说明。
